### ISSUE TITLE
Defective Yarn Lock file

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/Web-Dev-II-Frontend#19]
I've tried to install some packages but there seemed to be a `yarn.lock` issue when the last commit was merged to master. I am almost certain that it pertains to yarn lock file being altered incorrectly. Can someone create a separate repository and install all the current packages that we have in the master branch and create a pr that alters the current yarn lock file? Also, I believe that doing the same with `package-lock.json` because those might have some relation with each other

**Comment by sebastian-nunez** [comment]
1. What is the benefit or yarn?
2. Which are we going to use, yarn or npm? Currently, I've used npm exclusively to install packages. 
3. How do replicate this?
