### ISSUE TITLE
Design the scrollbar

### ISSUE THREAD

**Issue by styled-man** [upe-webdev-2/Web-Dev-II-Frontend#40]
On windows machines, The scrollbar looks very bad. It covers certain portions of the screen and other time it makes so you have to scroll horizontally to view the full screen.

I suggest giving it a custom design that Integrates with the page better or just hiding it completly

![image](https://user-images.githubusercontent.com/55722176/201088934-bdc743f3-497f-46fa-9fc2-25b08950cb99.png)

**Comment by GabrielPedroza** [comment]
This is definitely something to consider. Depending on how hard this actually would be to implement, I'd argue that it isn't an enhancement and more a needed design. I think the best way to approach this is to remove the unneeded scroll bars and find a lib or docs that'll make styling this very easy

**Comment by Rishav1707** [comment]
@styled-man Will you assign me this problem??

**Comment by Rishav1707** [comment]
@styled-man Scrollbar issue was resolved already, please close this issue.

![CodeClash _ Problem 1 - Google Chrome 13-11-2022 09_54_46](https://user-images.githubusercontent.com/97666287/201505666-26760376-ddce-4711-967a-26da9090c61b.png)
