### ISSUE TITLE
Clean the overall structure. Remove any credits from Ryosuke and anyone else associated to the Template (Will give credit in package.json and README.md))

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/Web-Dev-II-Frontend#5]

**Comment by sebastian-nunez** [comment]
On my "Playground" branch I modified the code to reflect CodeClash and not the person who made the template.

**Comment by GabrielPedroza** [comment]
Sounds great! Whenever it's ready, just make a pr and I'll review and merge it
